In [34]:
# Dependencies
import pandas as pd
import numpy as np
from os import path
from PIL import Image
import matplotlib.pyplot as plt
plt.style.use('seaborn')
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import nltk 
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [35]:
# Load and read CSV file
file = 'list_gz.csv'
df = pd.read_csv(file, index_col=0, encoding="ISO-8859-1")
df.head()

,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,
2384,https://www.airbnb.com/rooms/2384,20190922191701,2019-09-22,Hyde Park Private Room - Pleasant Walk to UChi...,You are invited to be the sole Airbnb guest in...,"The private bedroom has a queen size bed, beds...",You are invited to be the sole Airbnb guest in...,none,My apartment is one block from beautiful Jacks...,The basement laundry room hours are 8:00am to ...,...,t,f,strict_14_with_grace_period,f,f,1,0,1,0,2.97
4505,https://www.airbnb.com/rooms/4505,20190922191701,2019-09-22,One Great Apartment. 377 Great Reviews. 1 Bad ...,"We took the winter off, made things nicer arou...","We travel a lot, we know what people need. We...","We took the winter off, made things nicer arou...",none,NaN,NaN,...,t,f,moderate,f,f,1,1,0,0,2.98
7126,https://www.airbnb.com/rooms/7126,20190922191701,2019-09-22,Tiny Studio Apartment 94 Walk Score,A very small studio in a wonderful neighborhood.,This is a very small studio apartment with a ...,A very small studio in a wonderful neighborhoo...,none,"Ukrainian Village was just named ""Hottest Neig...",We really like our neighbors and want guests t...,...,f,f,moderate,f,f,1,1,0,0,2.89
9811,https://www.airbnb.com/rooms/9811,20190922191701,2019-09-22,Barbara's Hideaway - Old Town,One-bedroom hideaway tucked into Old Town step...,"This lovely one bedroom ""hideaway"" is located ...",One-bedroom hideaway tucked into Old Town step...,none,Chicagoâs Old Town neighborhood is squeezed ...,Vacation rental tax of 21.4 required in additi...,...,t,f,strict_14_with_grace_period,f,f,10,10,0,0,0.65
10945,https://www.airbnb.com/rooms/10945,20190922191701,2019-09-22,The Biddle House (#1),Beautiful first floor apartment in Historic Ol...,This 1st floor apartment has a queen size bed ...,Beautiful first floor apartment in Historic Ol...,none,NaN,3-4 Night Minimum depending on Season. Licens...,...,t,f,strict_14_with_grace_period,f,f,10,10,0,0,0.21

In [37]:
pd.set_option('display.max_rows', 110)
df.dtypes

listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
name                                             object
summary                                          object
space                                            object
description                                      object
experiences_offered                              object
neighborhood_overview                            object
notes                                            object
transit                                          object
access                                           object
interaction                                      object
house_rules                                      object
thumbnail_url                                   float64
medium_url                                      float64
picture_url                                      object
xl_picture_url                                  float64
host_id                                           int64
host_url                                         object
host_name                                        object
host_since                                       object
host_location                                    object
host_about                                       object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                            float64
host_is_superhost                                object
host_thumbnail_url                               object
host_picture_url                                 object
host_neighbourhood                               object
host_listings_count                               int64
host_total_listings_count                         int64
host_verifications                               object
host_has_profile_pic                             object
host_identity_verified                           object
street                                           object
neighbourhood                                    object
neighbourhood_cleansed                           object
neighbourhood_group_cleansed                    float64
city                                             object
state                                            object
zipcode                                          object
market                                           object
smart_location                                   object
country_code                                     object
country                                          object
latitude                                        float64
longitude                                       float64
is_location_exact                                object
property_type                                    object
room_type                                        object
accommodates                                      int64
bathrooms                                       float64
bedrooms                                        float64
beds                                            float64
bed_type                                         object
amenities                                        object
square_feet                                     float64
price                                            object
weekly_price                                     object
monthly_price                                    object
security_deposit                                 object
cleaning_fee                                     object
guests_included                                   int64
extra_people                                     object
minimum_nights                                    int64
maximum_nights                                    int64
minimum_minimum_nights                            int64
maximum_minimum_nights                            int64
minimum_maximum_nights                            int64
maximum_maximum_nights                            int64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                 object
has_availability                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                            object
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
first_review                                     object
last_review                                      object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                 object
license                                          object
jurisdiction_names                               object
instant_bookable                                 object
is_business_travel_ready                         object
cancellation_policy                              object
require_guest_profile_picture                    object
require_guest_phone_verification                 object
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
dtype: object

In [38]:
df = df.rename(columns={'neighbourhood_cleansed': 'Chicago Neighbourhoods', 'listing_url': 'AirBnB Listings', 'review_scores_rating': 'Avg Reviews Ratings','reviews_per_month': 'Reviews Per Month'})

# ChiTown AirBnB Rentals

In [39]:
TopNeighbourhoods = pd.DataFrame(df.groupby('Chicago Neighbourhoods')['AirBnB Listings'].nunique())
TopNeighbourhoods.sort_values(by=['AirBnB Listings'], ascending=False, inplace=True)
TopNeighbourhoods.head(5)

                        AirBnB Listings
Chicago Neighbourhoods
West Town                          1127
Near North Side                     852
Lake View                           780
Logan Square                        600
Loop                                527

Chicago Neighbourhoods with over 500 AirBnB listings

In [40]:
BottomNeighbourhoods = pd.DataFrame(df.groupby('Chicago Neighbourhoods')['AirBnB Listings'].nunique())
BottomNeighbourhoods.sort_values(by=['AirBnB Listings'], ascending=True, inplace=True)
BottomNeighbourhoods.head(10)

                        AirBnB Listings
Chicago Neighbourhoods
South Deering                         1
Mount Greenwood                       1
Montclare                             2
Avalon Park                           2
Clearing                              2
West Pullman                          3
Gage Park                             4
Edison Park                           4
Riverdale                             4
Roseland                              4

*Chicago Neighbourhoods with tmhe less than 5 AirBnB listings

In [41]:
Monthly_Reviews = pd.DataFrame(df.groupby('Chicago Neighbourhoods')['Reviews Per Month'].nunique())
Monthly_Reviews.sort_values(by=['Reviews Per Month'], ascending=False, inplace=True)
Monthly_Reviews.head(5)

                        Reviews Per Month
Chicago Neighbourhoods
West Town                             475
Lake View                             405
Logan Square                          350
Near North Side                       342
Lincoln Park                          281

*Neighbourhoods with the most reviews!